### ISSUE TITLE
Kindle Highlights design

### ISSUE THREAD

**Issue by hadynz** [jsmorabito/obsidian-design#48]
Hi 👋 ,

I notice you are a contributor to the excellent plugin of [obsidian-workspaces-plus][2] and come from a UX background.

Just wanted to ask if you would be open to contribute to another plugin that I currently author [obsidian-kindle-plugin][1].

The plugin currently has a minimalistic user experience. With a UX person on board, I think there is some interesting work that can be done to enhance the plugin:

* UI to see list of books and highlights in the vault
* Readwise like feature to show highlight of the day
* UI to see syncing progress, ignore syncing of certain books, etc

I am sure with you onboard you will also be coming up with other ideas that I'd be open to collaborate with you on. 

Let me know if you have any appetite. 

[1]: https://github.com/hadynz/obsidian-kindle-plugin
[2]: https://github.com/nothingislost/obsidian-workspaces-plus

**Comment by jsmorabito** [comment]
Hey @hadynz thanks for reaching out with this idea! I'm very interested in this problem space, but have a couple other side projects that I am prioritizing at the moment. I also have a Kobo eReader and not a Kindle (though I'm considering getting one now that they finally have warm light mode on the entry level models 🙂). Not being able to access my kobo notes outside of the device (without using a hacky method) has been a huge pain point and almost entirely discouraged me from taking notes in the ereader which is not good! I'm going to add this to my project board and will periodically chip away at the design challenges when I have time, especially when I get a Kindle haha. Thanks again for reaching out and sorry for the delayed response!

**Comment by hadynz** [comment]
Not a problem at all. Thanks for coming back to me @jsmorabito
